### ISSUE TITLE
Support .NET Core, .NET Standard

### ISSUE THREAD

**Issue by pmunin** [ekonbenefits/impromptu-interface#20]
Please support new frameworks .NET Core, .NET Standard

**Comment by jbtule** [comment]
not for myself: 
https://github.com/jfrijters/Managed.Reflection

**Comment by payoff** [comment]
Do you have any plan to release a compatible version?

**Comment by eric-swann-q2** [comment]
Hello, @jbtule we would also love to see a port of this to .Net core. Would be happy to contribute some effort as well. Are there any plans to get this moving forward?

**Comment by eric-swann-q2** [comment]
@jbtule Absolutely, if you have a good part to break off, give me a shout.

**Comment by jbtule** [comment]
Alright .net standard 2.0 work is under PR #23 

It didn't take that much to make it build. However the tests still need to be ported to run under .net framework and .net core.  All tests are passing for .net framework, but .net core :man_shrugging: who knows?

**Comment by jbtule** [comment]
So actually all the tests pass, after I fixed stuff in Dynamitey. So 7.0.1-beta  is under prereleases on nuget.    The best help now is to try and use it. There maybe syntactic breaking changes from 6.X but all the features should be there.

**Comment by eric-swann-q2** [comment]
Hey @jbtule, I ran into an issue in one of our libraries.  We were using CoerciveConvert in one location.  What is the replacement for that?  Just use ActLike?  Thanks!

**Comment by jbtule** [comment]
It's in the Dynamitey library `using Dynamitey;` ...  `Dynamic.CoerceConvert`

**Comment by eric-swann-q2** [comment]
Ah nice...perhaps I can just reference Dynamitey instead.

**Comment by jbtule** [comment]
If that's all you need yes.

**Comment by eric-swann-q2** [comment]
@jbtule What is the difference in behavior between CoerciveConvert and ActLike?  They seem to be accomplishing the same thing.

**Comment by jbtule** [comment]
Ah.

`ActLike` is interface proxying only. That's all it does, that is what the ImpromtpuInterface library now has been streamlined to only do. 

`CoerceConvert` tries EVERY conversion api on your platform's standard library to try and change your target object to the passed in type (which can be anything, not just an interface). If `ImpromptuInterface` has been referenced, and runtime `CoerceConvert` will try search out and try to use `ActLike` if you pass an interface as your type.

So if you are just doing Interface wrapping, use `ActLike`, if you are just dynamically converting types, use `CoerceConvert` if you need both, make sure you have ImpromptuInterface referenced so dynamitey can pick up the extra interface wrapping feature.

**Comment by eric-swann-q2** [comment]
Got it, thanks for the info.

**Comment by konne** [comment]
@jbtule 
what is you actual plan to release a stable nuget package?

**Comment by jbtule** [comment]
deployed as stable
