### ISSUE TITLE
feature: ActLike convert tuple

### ISSUE THREAD

**Issue by msalvexx** [ekonbenefits/impromptu-interface#38]
It will be nice for legibility if we can use ActLike() method from Tuples, converting this code example from:

```
var account = new
            {
                Id = "valid_id",
                Name = "valid_name",
                Email = "valid_email@mail.com",
                Password = "valid_password"
            }.ActLike<IAccount>();
```

To this:

```
var account = (
                Id: "valid_id",
                Name: "valid_name",
                Email: "valid_email@mail.com",
                Password: "valid_password"
            ).ActLike<IAccount>();
```

I am not sure if we are able to do this, because C# has some limitations on using Tuples, but it will be nice if we can have this kind of feature :heart_eyes:

**Comment by jbtule** [comment]
Unfortunately, Tuple names are only known at compile time, so nothing I can do.

Sometimes people use impromptu interface for things they know at both compile time and runtime like anonymous classes, as a work around to pass them outside of methods, and that works fine, however named tuples are the real the answer to that over impromptu interface.

**Comment by msalvexx** [comment]
Sadly, but I was already expecting this answer
Thanks for your comment
