### ISSUE TITLE
Updating ImpromptuInterface from 6.2.2 to 7.0.1 (latest version)

### ISSUE THREAD

**Issue by Bronzato1** [ekonbenefits/impromptu-interface#47]
My project currently references ImpromptuInterface 6.2.2 and it works great. I am in the process of updating all my nuget packages to latest version.

When updating ImpromptuInterface from 6.2.2 to 7.0.1 I got 2 errors:

- 'Impromptu' does not contain a definition for 'InvokeGet'
- 'Impromptu' does not contain a definition for 'GetMemberNames'

My code:

if (**Impromptu.GetMemberNames**(sourceObject).Any(x => x == newPropertyPath))
{
    var newSourceObject = **Impromptu.InvokeGet**(sourceObject, newPropertyPath);
}

It seems these methods does no longer exists. 
Any help is much appreciated.

**Comment by jbtule** [comment]
7.0 breaking change, those methods have moved to `Dynamic.GetMemberNames` and `Dynamic.InvokeGet` in Dynamitey. But they are identical and is a nuget dependency.

**Comment by Bronzato1** [comment]
Good to know. Thanks !
