### ISSUE TITLE
Build not passing + Proxy interfaces missing Custom Attributes

### ISSUE THREAD

**Issue by david-garcia-garcia** [ekonbenefits/impromptu-interface#51]
I've left a couple PR's.

One to add CustomAttributes to the generated proxy interfaces:

https://github.com/ekonbenefits/impromptu-interface/pull/49

Another one to fix the build process:

https://github.com/ekonbenefits/impromptu-interface/pull/50

**Comment by jbtule** [comment]
will be in next version
