### ISSUE TITLE
Do TryGetMember and TrySetMember Work?

### ISSUE THREAD

**Issue by rarcher** [ekonbenefits/impromptu-interface#58]
Does this library support using `DynamicObject` subclasses that provide their own implementations for `TryGetMember` and `TrySetMember`?  I am encountering an error when I try to do this, and issue #30 implies that it just doesn't work currently.

**Comment by jbtule** [comment]
It does, #30 is action referring to having forwarded members with `out` or 'in` rather than allowing dynamic implementations.  It works with anything that implements `System.Dynamic.IDynamicMetaObjectProvider`, which `DynamicObject` subclasses do.

**Comment by rarcher** [comment]
Okay, found the problem, finally.  It was unrelated to ImpromptuInterface.

Thank you very much for the information, and for the excellent library, sir!
